spring:
  application:
    name: example-elk
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/example-elk?useSSL=false
      username: root
      password: root
  jpa:
    show-sql: true
