spring:
  application:
    name: example-mq
eureka:
  client:
    service-url:
      defaultZone: http://124.221.93.112:8761/eureka/
  instance:
    prefer-ip-address: true


rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}

server:
  port: 10010
