version: "3.1"

services:
  nginx:
    image: nginx              # 镜像名称
    container_name: nginx     # 容器名字
    restart: always           # 开机自动重启
    ports:                    # 端口号绑定（宿主机:容器内）
      - "80:80"
      - "443:443"
    volumes: # 目录映射（宿主机:容器内）
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # 配置文件
      - ./log:/var/log/nginx          # 日志目录
      - ./html:/etc/nginx/html        # 网页目录
      - ./conf:/etc/nginx             #配置目录
